# Partie 1 : recharger data/offres.ndjson dans l'index "offres".

input {
  file {
    path => "/data/offres.ndjson"
    mode => "read"
    codec => "json"
    sincedb_path => "/dev/null"
    file_completed_action => "log"
    file_completed_log_path => "/usr/share/logstash/data/offres_lus.log"
  }
}

filter {
  # Exercice 1.2 :
  # volontairement vide afin d'observer les champs ajoutés par Logstash
  # et leur incompatibilité avec le mapping "dynamic": "strict".
}

output {
  elasticsearch {
    hosts => ["${ES_HOSTS}"]
    user => "${ES_USER}"
    password => "${ES_PASSWORD}"
    index => "offres"
    document_id => "%{id}"
    action => "index"
    data_stream => "false"
    manage_template => false
  }
}
